### ISSUE TITLE
Creates duplicate child-records on copy/paste

### ISSUE THREAD

**Issue by thegass** [team23/t23_inline_container#1]
I tried this extension with b13/container version 2.1.0
If your extension is active, if i copy / paste a container to an other page the child items get duplicated.

**Comment by timdreier** [comment]
Thank you for the info, I’ll have a look on it!

**Comment by timdreier** [comment]
Hi @thegass,
should be fixed with version 0.0.4!

**Comment by thegass** [comment]
thanks. will try on wednesday when i'm back in the office.
