### ISSUE TITLE
Issue with inline container 

### ISSUE THREAD

**Issue by ghost** [team23/t23_inline_container#12]
When i insert new content element it returns two content elements with two different languages (FR & EN).
Did you have an idea how can i fix this error?

![tt](https://github.com/team23/t23_inline_container/assets/80040569/9978bdf8-118d-49cf-8aff-7482ca2755fb)

**Comment by timdreier** [comment]
Hi @Hajerbenlassoued,
Could you add more steps on how to reproduce your issue?

We also use the Extension in multi-language setups without issues so far.

**Comment by timdreier** [comment]
Hi @Hajerbenlassoued,
I recently found a similar issue. Could you try if version `0.0.13-rc4` fixes your issue too?

**Comment by timdreier** [comment]
Should be fixed in `0.0.13` :)
