### ISSUE TITLE
fix for https://github.com/team23/t23_inline_container/issues/1 "breaks" container-sorting

### ISSUE THREAD

**Issue by thegass** [team23/t23_inline_container#2]
First, thanks for looking into the duplicate-child problem.
that problem is "fixed".

but now, after copy the container elements have the "wrong" sorting according to b13/container.

Example:
Container & Childs after copy

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/101392/200826107-cf1de021-c65b-43d4-98af-1776d5f1872f.png">

now i run the sorting-update script from b13/container

```
./vendor/bin/typo3cms container:sorting --apply 
container uid: 94768, pid 7723 must be fixed
```
Container & Childs after update script

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/101392/200827935-2ef18a49-6312-497c-85e0-77a6b84c9f3b.png">

I'm not 100% sure if this leads to problems (looks ok in backend and frontend) but the issue remains, that the container extension thinks the sorting is wrong (wants the container itself sorted before the childs).

**Comment by timdreier** [comment]
Hi, thank you @thegass! I'll have a look at it.

Probably the best solution would be to disable the default way typo3 handles copying and use the way how container handles it.

**Comment by timdreier** [comment]
@thegass the issue should be fixed in Version 0.0.6!

**Comment by thegass** [comment]
@timdreier 
thanks. but should https://github.com/team23/t23_inline_container/blob/00b9eae8b60561ae2573e7337b16c0eace7a65cf/Classes/Hooks/DataHandler.php#L26 not be `if (in_array($command, ['copy', 'localize']) && $table === 'tt_content') {`

**Comment by timdreier** [comment]
Sure, don't know how I forgot that. Is fixed, thanks a lot!
